### ISSUE TITLE
To be even more successful, make sure that package manager is also installed. 

### ISSUE THREAD

**Issue by levibostian** [levibostian/bins#11]
You can't `brew install X` if `brew` is also not installed. 

Proposal: bins is good at installing commands. Well, let's have it be able to install the package manager, too! 

```yml
bins:
  - binary: sourcery 
    version: 
      requirement: "^2.0.0"
    installMethods: [brew] // shorthand
    installMethods: 
      - id: brew // in case you need to override args, use long version 
        binary: "tap/foo/foo"

installer:
  - id: brew // used to be identified in bins.installMethods
    binary: brew // used to check if installed. just like bins
    installCommand: "/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    installTemplate: "brew install {{.Binary}}"
    updateTemplate: "brew upgrade {{.Binary}}"
```

This changes the config yml for installing. But, what is nice is that we can bundle `bins` with a default set of installers like brew, gem, npm. makes it easier for you to create config file. 

Then, the CLI will first make sure that when you pick an install method, we make sure the installer is also installed. 

- [X] Edit config file to use installers. 
- [x] Assert that installers are installed. Help install them if not. 
- [x] Ask what installer you would like to use if you have a preference. 
- [x] Bundle popular installers in the CLI so users dont need to define all installers.
